# Generated by Django 4.2.2 on 2023-06-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_full_name_user_name_user_password_and_more'),
    ]

    operations = [
        migrations.RenameField('User', 'nickname', 'username'),
    ]
