# Generated by Django 4.2.2 on 2023-06-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230622_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(db_column='username', default=None, max_length=200, verbose_name='username'),
            preserve_default=False,
        ),
    ]
