# Generated by Django 4.2.2 on 2023-09-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
    ]
