# Generated by Django 4.2.2 on 2023-08-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_status_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='users',
        ),
    ]
